#!/bin/bash

hsdir="$HOME/.config/herbstluftwm/"

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# clear settings
hc keyunbind --all
hc mouseunbind --all
hc unrule -F

Mod=Mod4   # Use the super key as the main modifier

############################
#         KEYBINDS         #
############################
hc keybind $Mod-Shift-Escape quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Shift-0 spawn ~/bin/suspend.sh

# terminal
hc keybind $Mod-Return spawn kitty
# lock
hc keybind $Mod-l spawn slock
# screenshot (selection to clipboard)
hc keybind Print spawn $hsdir/prtsc.sh

# media keys
# volume
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume @DEFAULT_SINK@ -1%
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume @DEFAULT_SINK@ +1%
hc keybind XF86AudioMute spawn pactl set-sink-mute @DEFAULT_SINK@ toggle

# mic
hc keybind XF86AudioMicMute spawn pactl set-source-mute @DEFAULT_SOURCE@ toggle

# player
#hc keybind XF86WakeUp-space spawn playerctl play-pause
hc keybind XF86Tools spawn playerctl play-pause
hc keybind XF86Search spawn playerctl next
hc keybind XF86LaunchA spawn playerctl previous

# brightness
hc keybind XF86MonBrightnessUp spawn light -A 5
hc keybind XF86MonBrightnessDown spawn light -U 5

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-Shift-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 horizontal max vertical grid    \
               , cycle_layout +1

# Change gaps
hc keybind $Mod-g cycle_value frame_gap 10 5

# Show hide frames
hc keybind $Mod-n cycle_value always_show_frame 0 1
hc keybind $Mod-m cycle_value frame_normal_opacity 0 40

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#878787'
hc set frame_border_normal_color '#202020'
hc set frame_bg_normal_color '[0]#878787'
hc set frame_bg_active_color '[0]#878787'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_active_opacity 0
hc set frame_normal_opacity 0
hc set frame_transparent_width 0
hc set frame_gap 3

hc attr theme.active.color '#878787'
hc attr theme.normal.color '#878787'
hc attr theme.urgent.color '#0087af'
hc attr theme.inner_width 2
hc attr theme.inner_color '#878787'
hc attr theme.border_width 0
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color '#af5f5f'
hc attr theme.active.inner_color '#af5f5f'
hc attr theme.active.outer_color '#878787'
hc attr theme.background_color '[0]#878787'

hc set window_gap 1
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1
hc set focus_stealing_prevention 1

# rules
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

xsetroot -solid '#282828'
numlockx on &
albert &

feh --bg-scale ~/Pictures/wallpapers/plants1.jpg

# find the panel
panel=$hsdir/launch.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
    hc pad $monitor 22 0 0 0
done

